"""Initial comprehensive educational platform schema

Revision ID: 92b01a060107
Revises: 
Create Date: 2025-09-07 15:33:09.684419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92b01a060107'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatwoot_contact_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatwoot_contact_mappings_contact_id'), 'chatwoot_contact_mappings', ['contact_id'], unique=True)
    op.create_index(op.f('ix_chatwoot_contact_mappings_phone'), 'chatwoot_contact_mappings', ['phone'], unique=False)
    op.create_table('questions_bank',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forms', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blooms_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blooms_descriptor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('learning_standards', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('answer_page', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chapter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assessment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_latex', sa.Boolean(), nullable=True),
    sa.Column('contains_calculations', sa.Boolean(), nullable=True),
    sa.Column('knowledge_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('knowledge_snippet_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_bank_blooms_level'), 'questions_bank', ['blooms_level'], unique=False)
    op.create_index(op.f('ix_questions_bank_chapter_name'), 'questions_bank', ['chapter_name'], unique=False)
    op.create_index(op.f('ix_questions_bank_chapter_number'), 'questions_bank', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_questions_bank_difficulty_level'), 'questions_bank', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_bank_language'), 'questions_bank', ['language'], unique=False)
    op.create_index(op.f('ix_questions_bank_source'), 'questions_bank', ['source'], unique=False)
    op.create_index(op.f('ix_questions_bank_subject'), 'questions_bank', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_bank_type'), 'questions_bank', ['type'], unique=False)
    op.create_table('subjects',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('book_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_book_code'), 'subjects', ['book_code'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('tier_quota_configs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('daily_quiz_limit', sa.Integer(), nullable=False),
    sa.Column('daily_quiz_limit_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('daily_message_limit', sa.Integer(), nullable=True),
    sa.Column('daily_message_limit_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollover_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PREMIUM', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('current_subjects', sa.JSON(), nullable=True),
    sa.Column('focus_subjects', sa.JSON(), nullable=True),
    sa.Column('form_level', sa.Integer(), nullable=True),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('school_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('chatwoot_user_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_contact_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_user_id')
    )
    op.create_index(op.f('ix_users_channel'), 'users', ['channel'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('chatwoot_conversation_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_inbox_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('chatwoot_conversation_id')
    )
    op.create_index(op.f('ix_chat_sessions_channel'), 'chat_sessions', ['channel'], unique=False)
    op.create_index(op.f('ix_chat_sessions_external_user_id'), 'chat_sessions', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('daily_quiz_quotas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('last_question_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('questions_attempted >= 0 AND questions_answered >= 0', name='positive_quotas'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quota_date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_quiz_quotas_quota_date'), 'daily_quiz_quotas', ['quota_date'], unique=False)
    op.create_index(op.f('ix_daily_quiz_quotas_user_id'), 'daily_quiz_quotas', ['user_id'], unique=False)
    op.create_table('daily_user_quotas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('quota_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('count >= 0', name='positive_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quota_date', 'quota_type', name='uq_user_date_type')
    )
    op.create_index(op.f('ix_daily_user_quotas_quota_date'), 'daily_user_quotas', ['quota_date'], unique=False)
    op.create_index(op.f('ix_daily_user_quotas_quota_type'), 'daily_user_quotas', ['quota_type'], unique=False)
    op.create_index(op.f('ix_daily_user_quotas_user_id'), 'daily_user_quotas', ['user_id'], unique=False)
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spot_questions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_questions_difficulty_level'), 'spot_questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_spot_questions_subject_id'), 'spot_questions', ['subject_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_created_at'), 'threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_threads_is_active'), 'threads', ['is_active'], unique=False)
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    op.create_table('chat_session_messages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rag_chunks', sa.JSON(), nullable=True),
    sa.Column('chatwoot_message_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chatwoot_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chatwoot_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_message_id')
    )
    op.create_index(op.f('ix_chat_session_messages_role'), 'chat_session_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_session_messages_session_id'), 'chat_session_messages', ['session_id'], unique=False)
    op.create_table('payment_links',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_tier', sa.Enum('FREE', 'PREMIUM', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_session_id'), 'payment_links', ['session_id'], unique=False)
    op.create_index(op.f('ix_payment_links_status'), 'payment_links', ['status'], unique=False)
    op.create_index(op.f('ix_payment_links_user_id'), 'payment_links', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions_bank.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_is_correct'), 'quiz_attempts', ['is_correct'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_session_id'), 'quiz_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('spot_question_attempts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['spot_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_question_attempts_is_correct'), 'spot_question_attempts', ['is_correct'], unique=False)
    op.create_index(op.f('ix_spot_question_attempts_question_id'), 'spot_question_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_spot_question_attempts_session_id'), 'spot_question_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_spot_question_attempts_user_id'), 'spot_question_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_question_attempts_user_id'), table_name='spot_question_attempts')
    op.drop_index(op.f('ix_spot_question_attempts_session_id'), table_name='spot_question_attempts')
    op.drop_index(op.f('ix_spot_question_attempts_question_id'), table_name='spot_question_attempts')
    op.drop_index(op.f('ix_spot_question_attempts_is_correct'), table_name='spot_question_attempts')
    op.drop_table('spot_question_attempts')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_session_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_is_correct'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_payment_links_user_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_status'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_session_id'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_index(op.f('ix_chat_session_messages_session_id'), table_name='chat_session_messages')
    op.drop_index(op.f('ix_chat_session_messages_role'), table_name='chat_session_messages')
    op.drop_table('chat_session_messages')
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_is_active'), table_name='threads')
    op.drop_index(op.f('ix_threads_created_at'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_spot_questions_subject_id'), table_name='spot_questions')
    op.drop_index(op.f('ix_spot_questions_difficulty_level'), table_name='spot_questions')
    op.drop_table('spot_questions')
    op.drop_table('session')
    op.drop_index(op.f('ix_daily_user_quotas_user_id'), table_name='daily_user_quotas')
    op.drop_index(op.f('ix_daily_user_quotas_quota_type'), table_name='daily_user_quotas')
    op.drop_index(op.f('ix_daily_user_quotas_quota_date'), table_name='daily_user_quotas')
    op.drop_table('daily_user_quotas')
    op.drop_index(op.f('ix_daily_quiz_quotas_user_id'), table_name='daily_quiz_quotas')
    op.drop_index(op.f('ix_daily_quiz_quotas_quota_date'), table_name='daily_quiz_quotas')
    op.drop_table('daily_quiz_quotas')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_external_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_channel'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_channel'), table_name='users')
    op.drop_table('users')
    op.drop_table('tier_quota_configs')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_book_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_questions_bank_type'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_subject'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_source'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_language'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_difficulty_level'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_chapter_number'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_chapter_name'), table_name='questions_bank')
    op.drop_index(op.f('ix_questions_bank_blooms_level'), table_name='questions_bank')
    op.drop_table('questions_bank')
    op.drop_index(op.f('ix_chatwoot_contact_mappings_phone'), table_name='chatwoot_contact_mappings')
    op.drop_index(op.f('ix_chatwoot_contact_mappings_contact_id'), table_name='chatwoot_contact_mappings')
    op.drop_table('chatwoot_contact_mappings')
    # ### end Alembic commands ###
