"""Add contact mapping table

Revision ID: b9470a002792
Revises: 501ce4feb3d0
Create Date: 2025-09-07 13:04:50.724281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9470a002792'
down_revision: Union[str, Sequence[str], None] = '501ce4feb3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatwoot_contact_mappings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatwoot_contact_mappings_contact_id'), 'chatwoot_contact_mappings', ['contact_id'], unique=True)
    op.create_index(op.f('ix_chatwoot_contact_mappings_phone'), 'chatwoot_contact_mappings', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatwoot_contact_mappings_phone'), table_name='chatwoot_contact_mappings')
    op.drop_index(op.f('ix_chatwoot_contact_mappings_contact_id'), table_name='chatwoot_contact_mappings')
    op.drop_table('chatwoot_contact_mappings')
    # ### end Alembic commands ###
